return {
  [0] =  {f="rest",i="Rest note"},
  [1] =  {f="A", i="Note A"},
  [2] =  {f="As",i="Note A#"},
  [3] =  {f="B", i="Note B"},
  [4] =  {f="C", i="Note C"},
  [5] =  {f="Cs",i="Note C#"},
  [6] =  {f="D", i="Note D"},
  [7] =  {f="Ds",i="Note D#"},
  [8] =  {f="E", i="Note E"},
  [9] =  {f="F", i="Note F"},
  [10] = {f="Fs",i="Note F#"},
  [11] = {f="G", i="Note G"},
  [12] = {f="Gs",i="Note G#"},
  [13] = {f="alt1",i="Alt 1"},
  [14] = {f="alt2",i="Alt 2"},
  [15] = {f="alt3",i="Alt 3"},
}
